### PR TITLE
Master

### PR DESCRIPTION
**Pull request by marc-hanheide**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
So @RaresAmbrus you should decide if this can be merged. In my view, hydro-devel should be the main branch. Once this is merged we can try to release it, but first, did you check license, install targets and email addresses?

**Comment by RaresAmbrus** [comment]
@marc-hanheide I'm not 100% sure about the license - OpenNI2 is released under the Apache License (http://en.wikipedia.org/wiki/Apache_License), which is different from what we've been using for other packages. But we're not modifying the original OpenNi2 code anyway, just using it as a submodule, so maybe we can stick to our usual MIT license scheme? 
I haven't checked the install targets for the OpenNI2 submodule - since that has just a makefile, I'll have to export the binaries and headers manually from the `openni_wrapper` `CMakeLists.txt`.

**Comment by marc-hanheide** [comment]
I'm not an expert in this. But would you be happy to simply also adopt an Apache license?

**Comment by RaresAmbrus** [comment]
It doesn't matter much to me which one we choose, I guess the easiest would be to go with the Apache License thus avoiding any conflicts. 

Here's a comparison between Apache and BSD/MIT: http://stackoverflow.com/questions/40100/apache-license-vs-bsd-vs-mit

Seems like Apache is more modern than MIT and slightly more restrictive, at least according to this thread. Also the preferred license by Google ;)

**Comment by marc-hanheide** [comment]
go4it

**Pull request merged**
