### PR TITLE
Set up install rules for openni_wrapper and OpenNI2

### PR DESCRIPTION
**Pull request by RaresAmbrus**

### CODE REVIEW

**Comment by RaresAmbrus** [comment]
@marc-hanheide I still have the `link_directories(${OPENNI2.2_DIR}/OpenNI2/Bin/x64-Release)` problem, I don't have a 32 bit system to figure out where the binaries will be installed. 
Otherwise things seem to be working out of the install folder, so maybe this can be released now?

**Comment by marc-hanheide** [comment]
I'll release it

**Comment by marc-hanheide** [comment]
on a second thought, the `link_directories(${OPENNI2.2_DIR}/OpenNI2/Bin/x64-Release)` won't work on a release system as the source dir won't be exported. You can test this by running `catkin_make install` and then deleting/moving the source workspace you installed from. Then a dependent package will, I assume, not be able to link properly, will it?

Maybe you can use the `make release` target in OpenNI2 and extract the tar that is created into `CMAKE_INSTALL_PREFIX/lib/OpenNI2` or similar with a custom install target? You definitely want to use the `${CATKIN_PACKAGE_LIB_DESTINATION}` variable in an install target to install the libs into.

**Comment by RaresAmbrus** [comment]
I already have this 

```
install(DIRECTORY ${OPENNI2.2_DIR}/OpenNI2/Include/.
  DESTINATION ${CATKIN_GLOBAL_INCLUDE_DESTINATION}/OpenNI2/Include
)

install(DIRECTORY ${OPENNI2.2_DIR}/OpenNI2/Bin/x64-Release/.
  DESTINATION ${CATKIN_GLOBAL_LIB_DESTINATION}
)

```

which copies all the OpenNI2 headers and libraries. That should do it, right? 

I've performed the test you described - running `catking_make install` and then moving the workspace; it worked. 

Maybe I should just add a separate linking command for the `x86` case ? I guess it would be built in `OpenNI2/Bin/x86-Release`.

**Pull request merged**
