### PR TITLE
Fixed some dependencies and maintainer email

### PR DESCRIPTION
**Pull request by RaresAmbrus**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I think the opencv dependencies are incorrect. This should be using cv_bridge throughout I suppose?

**Comment by RaresAmbrus** [comment]
@marc-hanheide I fixed the opencv stuff, but I'm still getting an error:

```
Linux/XnLinuxUSB.cpp:29:31: fatal error: libusb-1.0/libusb.h: No such file or directory
```

I've added  `libusb-dev` and `libudev-dev` to package.xml and CMakeLists.txt. 

Any ideas what could be wrong? Thanks!

**Comment by marc-hanheide** [comment]
Did you check that this file is actually installed by those packages. `dpkg -S /usr/include/libusb-1.0/libusb.h` could tell you

**Comment by RaresAmbrus** [comment]
@marc-hanheide thanks for the tip, it was in fact `libusb-1.0-0-dev` and not `libusb-dev`. Let's see what's next.

**Comment by marc-hanheide** [comment]
Have you made any progress towards the release?

**Comment by marc-hanheide** [comment]
This misses java dependency in `package.xml`: `<buildtool_depend>java</buildtool_depend>`

**Comment by RaresAmbrus** [comment]
Added it, thanks!

**Comment by marc-hanheide** [comment]
Even though jenkins is still trying... here's something else to work on:
`../../../ThirdParty/GL/GL/glut.h:59:20: fatal error: GL/glu.h: No such file or directory`

**Comment by RaresAmbrus** [comment]
I guess these are all the openni2 dependencies; hopefully this is the last one ...

**Comment by marc-hanheide** [comment]
hooray!

**Comment by marc-hanheide** [comment]
Oh, I merged this, but only now realised that this was against master, and not hydro-devel? Which branch shall we use? I think hydro devel. So I'll open another PR to merge this into hydro-devel?

**Comment by RaresAmbrus** [comment]
Let me check the history. Since this repository was added after we migrated to hydro, there was no original master branch which was then copied into a hydro branch, as far as I remember. I'll just take a look at the history and see where the two branches come from.

**Pull request merged**
