### PR TITLE
Update OpenNI2 from occipital/OpenNI2.

### PR DESCRIPTION
**Pull request by cburbridge**
This pulls in the latest version of OpenNI2 from https://github.com/occipital/OpenNI2, solving issue #14.

@RaresAmbrus if you are ok with this then please merge so that I can make an indigo release. If you have a better way of including the upstream OpenNI changes then that would be nice.

### CODE REVIEW

**Comment by cburbridge** [comment]
This PR is into hydro-devel. It might be better in an indigo-devel branch....

**Comment by RaresAmbrus** [comment]
@cburbridge should I create an indigo-devel branch for it then? Otherwise looks ok, I'll test on the robot in a bit and get back to you. Thanks for doing this. 
Since we're not using submodules anymore I don't know if there's an easier way to pull stuff from upstream or other remotes.

**Comment by RaresAmbrus** [comment]
This code doesn't really change much, except to add the `pthread` library and remove some includes; I guess what fixes https://github.com/strands-project/openni_wrapper/issues/14 is `export ALLOW_WARNINGS = 1`  ?

**Comment by cburbridge** [comment]
I think so, but the pthread library is important too otherwise it does not link. 
Jenkins has already tested that is compiles ok with hyrdo, so I guess these changes wont make any difference there.

**Comment by RaresAmbrus** [comment]
Works on the robot, both in hydro and indigo. I'll create an indigo-devel branch anyway.

**Pull request merged**
