### PR TITLE
Moved OpenNI2 into package

### PR DESCRIPTION
**Pull request by marc-hanheide**
in order to release this package, the submodule needs to be within the package itself. This pull requests aims to achieve this.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
this shall lead to #4

**Comment by marc-hanheide** [comment]
@RaresAmbrus can you please confirm this pull request. It built on jenkins and should be fine, but I want you to have a last check. Next step will be releasing it.

**Comment by marc-hanheide** [comment]
Oh, and happy birthday @raresambrus

**Comment by RaresAmbrus** [comment]
Thanks for the wishes @marc-hanheide  :D 
I was out over the weekend, I'll take a look at this and merge it now. Thanks for moving things around, I had no idea the submodule had to be part of the package, though it does make sense.

**Pull request merged**
